name: Build Heroes III AI Applications

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Build Windows executables
        run: |
          pip install pyinstaller opencv-python pillow pyautogui numpy
          pyinstaller --onefile --windowed --name "HoMM3-Adaptive-AI" --add-data "VERSION.txt;." homm3_adaptive_ai.py
          pyinstaller --onefile --windowed --name "HoMM3-Realistic-AI" --add-data "VERSION.txt;." homm3_realistic_ai.py
          pyinstaller --onefile --windowed --name "HoMM3-AI-Game" --add-data "VERSION.txt;." homm3_game_simulator.py
          
      - name: Verify executable exists
        run: |
          dir dist
          echo "Executables built successfully"
          
      - name: Upload Windows executables
        uses: actions/upload-artifact@v4
        with:
          name: HoMM3-AI-Windows
          path: |
            dist/HoMM3-Adaptive-AI.exe
            dist/HoMM3-Realistic-AI.exe
            dist/HoMM3-AI-Game.exe

  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            HoMM3-AI-Windows/HoMM3-Adaptive-AI.exe
            HoMM3-AI-Windows/HoMM3-Realistic-AI.exe
            HoMM3-AI-Windows/HoMM3-AI-Game.exe
          body: |
            ## Heroes III Advanced AI Collection v${{ github.ref_name }}
            
            **Three powerful AI opponents - download and run immediately!**
            
            ### HoMM3-Adaptive-AI.exe ⭐ MACHINE LEARNING AI
            - **Creates and evolves strategies dynamically**
            - Learns from every game and adapts approaches
            - Generates novel strategies when standard ones fail
            - Develops personalized counter-strategies
            - Saves learning data between sessions
            
            ### HoMM3-Realistic-AI.exe ⚖️ FAIR COMPETITION
            - Respects fog of war completely
            - No unfair advantages or information access
            - Human-like decision timing and mistakes
            - Fair competitive gameplay
            
            ### HoMM3-AI-Game.exe 🎮 STANDALONE GAME
            - Complete Heroes III-style strategy game
            - Practice immediately without setup
            
            **Requirements:** Windows with Heroes III for the AI Controller versions.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
