name: Build Simple HoMM3 AI Executable
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Build Windows executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --windowed --name "HoMM3-AI-Opponent" homm3_ai_simple.py
          
      - name: Verify executable exists
        run: |
          dir dist
          echo "Executable built successfully"
          
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: HoMM3-AI-Opponent-Windows
          path: dist/HoMM3-AI-Opponent.exe
  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            HoMM3-AI-Opponent-Windows/HoMM3-AI-Opponent.exe
          body: |
            ## Heroes III AI Opponent v${{ github.ref_name }}
            
            **Download and double-click to run - no installation required!**
            
            ### What it does:
            - Provides intelligent AI opponent for Heroes III (VCMI)
            - Monitors game files and makes strategic decisions
            - Simple GUI for configuration and monitoring
            
            ### How to use:
            1. Download HoMM3-AI-Opponent.exe
            2. Double-click to run
            3. Set your VCMI game state file path
            4. Set where AI should write decisions
            5. Click "Start AI" and play VCMI
            
            The AI will automatically respond to your game moves!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
