name: Build Heroes III AI Applications

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Build Windows executables
        run: |
          pip install pyinstaller opencv-python pillow pyautogui
          pyinstaller --onefile --windowed --name "HoMM3-AI-Controller" --add-data "VERSION.txt;." homm3_real_ai.py
          pyinstaller --onefile --windowed --name "HoMM3-AI-Game" --add-data "VERSION.txt;." homm3_game_simulator.py
          
      - name: Verify executable exists
        run: |
          dir dist
          echo "Executables built successfully"
          
      - name: Upload Windows executables
        uses: actions/upload-artifact@v4
        with:
          name: HoMM3-AI-Windows
          path: |
            dist/HoMM3-AI-Controller.exe
            dist/HoMM3-AI-Game.exe

  create-release:
    needs: [build-windows]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            HoMM3-AI-Windows/HoMM3-AI-Controller.exe
            HoMM3-AI-Windows/HoMM3-AI-Game.exe
          body: |
            ## Heroes III AI Controller v${{ github.ref_name }}
            
            **Two AI applications - download and run immediately!**
            
            ### HoMM3-AI-Controller.exe ⭐ THE REAL THING
            - **Controls actual Heroes III game using computer vision**
            - Analyzes game screen and makes intelligent decisions
            - Automates mouse/keyboard to play the real game
            - Works with any Heroes III version (original, HD, VCMI)
            
            **How to use the Controller:**
            1. Start Heroes III and begin a game
            2. Run HoMM3-AI-Controller.exe
            3. Select AI strategy (exploration/aggressive/resource gathering)
            4. Click "Start AI" - it will take over and play for you!
            
            ### HoMM3-AI-Game.exe
            - Standalone Heroes III-style strategy game
            - Practice against AI without needing the real game
            
            **Requirements:** Windows with Heroes III for the Controller version.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
